# Generated by Django 3.0.8 on 2020-09-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteDJ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
